VERSION = '3.2.0'

API_BASE_URL = 'https://www.piracybound.com/api'
API_KEY_PREFIX = 'manilua_'

HTTP_TIMEOUT_DEFAULT = 30
HTTP_MAX_RETRIES = 5
HTTP_BASE_RETRY_DELAY = 2.0
HTTP_CHUNK_SIZE = 512 * 1024

API_USER_ID_CACHE_TTL = 300

DOWNLOAD_PROGRESS_UPDATE_INTERVAL = 0.10

USER_AGENT = f'manilua-plugin/{VERSION} (Millennium)'
